---
title: "Storing Zotero library on UQ RDM"
author: "Paul Melloy"
date: "2024-06-10"
---

## Webdavs 
Recently I learnt that The University of Queensland's 
[Research Data Maganger (RDM)](https://rdm.uq.edu.au/) supported WebDav apps. 
Why is this exciting and worth blogging about?  

## Zotero  
I use [Zotero](https://www.zotero.org/) as my citation manager. 
It is free and open source, which means I don't run into issues when jumping between
academia jobs when I want to bring my virtual library with me.
However, I still have issues when I lose all the attachments to my records.
From time to time I have subscribed to Zotero, to back-up my attachment library 
of PDFs. 
However currently I am not subscribed and recently my hard-drive failed on my 
work laptop, which mean't I lost the links to all my stored attachment library.  

Zotero also offers functionality where users can back-up their attachments through
[WebDav software](https://www.zotero.org/support/sync). 

While working at The University of Southern Queensland I was able to use the ARDC
Cloudstor with WebDav to back-up and sync my library, however in 2022 this service
was discontinued.  

I have been eying off purchasing [pCloud storage](https://forums.zotero.org/discussion/75204/use-of-pcloud-as-webdav-storage-how-to-set-it-up),
which would allow me to store data and access it through WebDav.
I have also been considering creating a home server with WebDav storage.

## U
Only recently I learnt when trying to access data from my UQ RDM from a ARDC nectar
instance I was made aware of the WebDav support.
