---
title: "2504_KnowledgeTruthMoneyPowerless"
output: html_document
---

# Knowledge, Truth, Money and Powerless – Universities (a reponse)  

 > **These view are my own and have no connection to my employer.**  
 

This is an open reply to a mate, Olger Quicy, a guest writer for the blog 
[“Devaluating Everything. Universities”](https://www.fresheconomicthinking.com/p/devaluating-everything-universities). 

I have to disagree with the views of my beguiling friend Mr Quincy, that 
“technology, feminisation, and immigration” are the decay of universities. 
However, while I have to agree that universities in Australia are not the 
prestigious institutions they once were. 
It is easy to compare the triumphs of the past to the disappointments of today 
and superimpose our prejudices. 
I identify the views of Mr Quincy as being narrow, in mind and scope.  

It is indeed a frustrating scene the rot that has established in universities 
and it is not the fault of progressive ideals. 
In my view, it is indeed the opposite, and where I superimpose my prejudices 
with my disappointment on the university degree-mills today, a successful 
conservative agenda to control the narrative.  

Technology is developing at an astounding rate, and does indeed have 
universities on the back foot. Large language models (LLMs), or less accurately 
artificial intelligence (AI) have indeed changed the game, just as the advert of
the internet prior to plagiarism checkers. 
As our friend has let us sail into the past to examples where technology has 
caused upheaval in our ability to judge, have students done the work to deserve 
the degree. 
Spell checkers were once seen as cheating, typewriters could obfuscate the true 
authors of written assessment. 
The advent of the printing press provides an analogous to the Internet of today. 
With the ease of access to books, for commoners to write and disseminate knowledge
without the oversight from experts in the church or monasteries who will value the 
knowledge of university experts. 
LLMs are the most recent procession of technological tools we navigate in the 
treacherous waters of learning and gaining knowledge.  

At this stage I wish to encourage the readers to step back and take a wider view, 
metaphorically and literally. 
Right now you do not read this in a magazine, or newspaper, book or bulletin 
board. 
I don’t stand before you on my soap box, you likely read this on your digital 
devices which some in the past say have cheapened access to knowledge. 
Do you have notifications screaming at you the latest incredulous announcement 
by President Trump and interfering with your focus read this piece. 
Are there pictures adorning the words which might have once been viewed as 
immature adornments to rigorous literature. 
Do you have a fact-checker plug-in prompting for second opinions.  

Taking a wider view, will universities die due to technology? 
Or do they serve as a necessary hand on the tiller to navigate seas in a 
maelstrom of competing information. By now I hope you see the lighthouse through 
the squalls and recognise that these beacons of light ‘should be’ our universities. 
Institutions that provide guidance in a ‘post-truth’ world.  

Right now I chart course to the provocation that 
[feminisation](https://en.wikipedia.org/wiki/Feminization_(sociology)) is associated with 
loss in value. 
I feel this point has no solid argument, I could cry 
[‘correlation does not equate to causation’](https://www.tylervigen.com/spurious-correlations), 
however the statistician in me objects and points out a covariate can 
[mask](https://www.sciencedirect.com/science/article/pii/S0042698915002497) the 
causal inference. I apologise for no nautical themed metaphor here, but the 
[‘DAG’](https://en.wikipedia.org/wiki/Directed_acyclic_graph) I am gives you 
this this pun. Suffice to say, feminisation is profitable. 
As alluded to by Mr Quincy, other factors were at play during feminisation, and 
the patriarchy recognises women provide cheaper labour, it is simple economics.  

[The statistics show a higher proportion of men in full employment or study](https://www.abs.gov.au/statistics/people/education/education-and-work-australia/latest-release#engagement-in-work-and-or-study), 
especially engineering.
However of these, a higher proportion of females studying and not in the workforce.
The reality of Australia's current economy is that there are greater incentives 
for men to obtain free TAFE diplomas or apprenticeships towards high paying 
occupations in the construction sector than higher degrees through University. 
I regularly lament a sliding doors moment at age 18 while staking shelves at a 
supermarket, a customer offered me an apprenticeship as a builder. 
Had I taken it I would today be much better financially secure than my current 
career in academia and science.
It is my view the devaluing of higher degrees came before the feminisation and we
see today a shift in how the patriarchy is maintained.  


This leads me to Olgers final bug-bear, immigration. 
At this stage I feel the fatigue and will reward the reader with being as 
succinct as possible. 
From the turn of the century (2000), the change in University to the businesses 
models probably likely in 2008, (shortly after Olger completed his first 
university degree) 
[when the federal government introduced the 485 Graduate Visas](https://www.legislation.gov.au/F2022L00845/latest/text). 
This legislation permitted international graduates to extend their stay if they 
found work I high demand occupations.
I have met and worked with many immigrants who took advantage of this legislation
to gain citizenship in Australia. 
In 2018 one former workmate from Singapore conveyed their surprise the 
[Murugappan 'Biloela' family](https://en.wikipedia.org/wiki/Murugappan_family_asylum_claims)
did not make use of this avenue for Australian citizenship and said they must have been 
poorly informed.
Subsequent [2017 caps to the Commonwealth Grant Scheme (CGS)](https://universitiesaustralia.edu.au/policy-submissions/teaching-learning-funding/how-universities-are-funded/)
have led universities to focus less on domestic students and pivot to seek revenue 
from international students to maintain their employment of their staff.  

Today Universities are not what they were 20 years ago, and we should not be
surprised by this fact. 
Universities have had to be agile to adapt to changes in government legislation
that has effectively weaken their power in the Australian community.
I view the [changes to international student numbers](https://www.abc.net.au/news/2025-01-04/international-education-year-of-uncertainty-foreign-students/104765238) 
by the blue and red tie wearing politicians as mechanisms to further remove funding 
in order to reduce their power and capacity to counter conservative agendas which 
are regularly criticised by university academics.
They are merely using the guise of the housing crisis to push this agenda.

Finally it is my view education needs [reform internationally to sustain the essential
role of Universities into the future.](https://theconversation.com/we-need-to-change-the-way-universities-assess-students-starting-with-these-3-things-203048) 
Simply passing the required university subjects should not equate to having the 
knowledge to be awarded a degree.
Education needs to be undertaken so students graduate knowing what they know, but
crucially knowing what they don't know.
To achieve this we need to incentivise course students and coordinators to review 
assessments together, rather than receive a reductive score.  
